# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo', '0002_auto_20170313_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='goals',
            field=models.TextField(default=None, editable=False),
        ),
        migrations.AddField(
            model_name='module',
            name='language',
            field=models.CharField(choices=[('EN', 'English'), ('DE', 'German')], default=None, max_length=2),
        ),
        migrations.AddField(
            model_name='module',
            name='maxParticipants',
            field=models.IntegerField(default=9223372036854775807),
        ),
        migrations.AddField(
            model_name='module',
            name='methods',
            field=models.TextField(default=None, editable=False),
        ),
        migrations.AddField(
            model_name='module',
            name='minParticipants',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='module',
            name='subtitle',
            field=models.TextField(default=None, editable=False),
        ),
        migrations.AddField(
            model_name='module',
            name='sws',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='module',
            name='type',
            field=models.IntegerField(choices=[(0, 'Seminar'), (1, 'Workshop'), (2, 'Colloquium'), (3, 'Module'), (4, 'Course'), (5, 'Exercice'), (6, 'Excursion'), (7, 'Presentation')], default=None),
        ),
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.TextField(default=None, editable=False),
        ),
    ]
