# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo', '0004_auto_20170314_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.TextField(default='', editable=False),
        ),
        migrations.AlterField(
            model_name='module',
            name='goals',
            field=models.TextField(default='', editable=False),
        ),
        migrations.AlterField(
            model_name='module',
            name='language',
            field=models.CharField(choices=[('EN', 'English'), ('DE', 'German'), ('', '')], default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='module',
            name='methods',
            field=models.TextField(default='', editable=False),
        ),
        migrations.AlterField(
            model_name='module',
            name='place',
            field=models.IntegerField(choices=[(0, 'Freising'), (1, 'Garching'), (2, 'Garching-Hochbrück'), (3, 'Inner city'), (4, 'Other'), (5, '')], default=5),
        ),
        migrations.AlterField(
            model_name='module',
            name='subtitle',
            field=models.TextField(default='', editable=False),
        ),
        migrations.AlterField(
            model_name='module',
            name='sws',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='module',
            name='type',
            field=models.IntegerField(choices=[(0, 'Seminar'), (1, 'Workshop'), (2, 'Colloquium'), (3, 'Module'), (4, 'Course'), (5, 'Exercice'), (6, 'Excursion'), (7, 'Presentation'), (8, 'Other'), (9, '')], default=9),
        ),
    ]
