# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo', '0005_auto_20170314_1001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ('title', 'credits', 'time', 'id')},
        ),
        migrations.RenameField(
            model_name='module',
            old_name='credit',
            new_name='credits',
        ),
        migrations.AddField(
            model_name='module',
            name='organisers',
            field=models.TextField(default='', editable=False),
        ),
    ]
