# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo', '0006_auto_20170315_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='exam_details',
            field=models.TextField(default='', editable=False),
        ),
        migrations.AlterField(
            model_name='module',
            name='exam',
            field=models.IntegerField(choices=[(0, 'Written exam'), (1, 'Oral exam'), (2, 'paper'), (3, 'Other'), (4, '')], default=4),
        ),
        migrations.AlterField(
            model_name='module',
            name='language',
            field=models.CharField(choices=[('EN', 'English'), ('DE', 'German'), ('??', 'Other'), ('', '')], default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='module',
            name='sws',
            field=models.FloatField(default=0.0),
        ),
    ]
