# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo', '0008_auto_20170318_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='selections',
            field=models.BigIntegerField(default=0),
        ),
    ]
