# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo', '0009_module_selections'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseFormat',
            fields=[
                ('course_format', models.CharField(default='Not specified', max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('exam_type', models.CharField(default='Not specified', max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('language', models.CharField(default='Not specified', max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location', models.CharField(default='Not specified', max_length=500, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Personality',
            fields=[
                ('personality', models.CharField(default='Not specified', max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TestPerson',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('categories', models.ManyToManyField(to='modulo.Category')),
            ],
            options={
                'ordering': ('personality', 'name'),
            },
        ),
        migrations.RemoveField(
            model_name='testpersons',
            name='modules',
        ),
        migrations.AlterField(
            model_name='module',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo.Exam'),
        ),
        migrations.AlterField(
            model_name='module',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo.Language'),
        ),
        migrations.AlterField(
            model_name='module',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo.Location'),
        ),
        migrations.AlterField(
            model_name='module',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo.CourseFormat'),
        ),
        migrations.DeleteModel(
            name='TestPersons',
        ),
        migrations.AddField(
            model_name='testperson',
            name='modules',
            field=models.ManyToManyField(to='modulo.Module'),
        ),
        migrations.AddField(
            model_name='testperson',
            name='personality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo.Personality'),
        ),
    ]
