# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 04:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo', '0010_auto_20170328_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modulo.Exam'),
        ),
        migrations.AlterField(
            model_name='module',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modulo.Language'),
        ),
        migrations.AlterField(
            model_name='module',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modulo.Location'),
        ),
        migrations.AlterField(
            model_name='module',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modulo.CourseFormat'),
        ),
    ]
