# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 19:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo', '0012_auto_20170330_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modulo.Exam'),
        ),
        migrations.AlterField(
            model_name='module',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modulo.Location'),
        ),
    ]
