# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 08:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo', '0014_auto_20170402_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='language',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='modulo.Language'),
        ),
        migrations.AlterField(
            model_name='module',
            name='type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='modulo.CourseFormat'),
        ),
    ]
