# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo', '0015_auto_20170402_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseformat',
            name='course_format',
            field=models.CharField(default=None, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='language',
            name='language',
            field=models.CharField(default=None, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='personality',
            name='personality',
            field=models.CharField(default=None, max_length=200, primary_key=True, serialize=False),
        ),
    ]
