# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo', '0016_auto_20170402_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='credits',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='module',
            name='time',
            field=models.TimeField(blank=True, default='00:00'),
        ),
    ]
