# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-07 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo', '0017_auto_20170404_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='credits',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='time',
            field=models.TimeField(blank=True, default='00:00', null=True),
        ),
    ]
